/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.DrawInterface;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sa
 */
public class FormulaireImprim extends javax.swing.JFrame {

    /**
     * Creates new form FormulaireImprim
     */
    public FormulaireImprim() throws BadElementException, IOException {
        initComponents();
        pdf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void pdf() throws BadElementException, IOException{
      Document document = new Document();
      try
      {
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("pdf/recu.pdf"));
        document.open();
        
        //Add Image
        Image image1 = Image.getInstance("logo/lafarge.png");
        //Fixed Positioning
        image1.setAbsolutePosition(20, 770);
        //Scale to new height and new width of image
        image1.scaleAbsolute(180, 65);
        //Add to document        
        document.add(image1);
        
        Phrase ph = new Phrase();
        
        Chunk title = new Chunk("Reçu N°: 00124");
        ph.add(title);
        
        ph.add(Chunk.NEWLINE);        
        
        Chunk date = new Chunk("Date: " + new SimpleDateFormat("dd-MM-YYYY HH:mm").format(new Date()));
        ph.add(date);
        
        Paragraph pg = new Paragraph();
        pg.add(ph);
        pg.setAlignment(Element.ALIGN_RIGHT);
        
        Phrase ph1 = new Phrase();
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        
        Chunk name = new Chunk("Nom: El Maazouzi");
        ph1.add(name);
        
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        
        Chunk firstname = new Chunk("Prénom: Zakaria");
        ph1.add(firstname);
        
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        
        Chunk position = new Chunk("Position: Directeur de service");
        ph1.add(position);
        
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        
        Chunk nbrenfant = new Chunk("Nombre d'enfants: 2");
        ph1.add(nbrenfant);
        
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 
        
        Chunk ancienente = new Chunk("Anciéneté: 4 ans");
        ph1.add(ancienente);
        
        ph1.add(Chunk.NEWLINE); 
        ph1.add(Chunk.NEWLINE); 

        Paragraph pg1 = new Paragraph();
        pg1.add(ph1);
        pg1.setAlignment(Element.ALIGN_LEFT);
        
        Phrase ph2 = new Phrase();
        
        ph2.add(Chunk.NEWLINE); 
        ph2.add(Chunk.NEWLINE); 
        ph2.add(Chunk.NEWLINE); 
        ph2.add(Chunk.NEWLINE); 
        ph2.add(Chunk.NEWLINE);        
        Chunk signature = new Chunk("Signature");
        ph2.add(signature);
        
        Paragraph pg2 = new Paragraph();
        pg2.add(ph2);
        pg2.setAlignment(Element.ALIGN_RIGHT);
        
        document.add(pg);
        document.add(pg1);
        document.add(pg2);
        document.close();
        writer.close();
      } catch (DocumentException e)
      {
         e.printStackTrace();
      } catch (FileNotFoundException e)
      {
         e.printStackTrace();
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireImprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireImprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireImprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireImprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormulaireImprim().setVisible(true);
                } catch (BadElementException ex) {
                    Logger.getLogger(FormulaireImprim.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FormulaireImprim.class.getName()).log(Level.SEVERE, null, ex);
                }
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
